Add listen gem
LoadError: Could not load the 'listen' gem. Add `gem 'listen'` to the
development group of your Gemfile
/home/k0kubun/src/ghe.ckpd.co/tech/barbeque_engine/spec/dummy/config/environment.rb:5:in
`<top (required)>'